# Generated by Django 4.0.1 on 2022-01-29 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('email', models.EmailField(max_length=300, null=True, unique=True)),
                ('short_intro', models.CharField(max_length=200, null=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='profiles/male.png', null=True, unique=True, upload_to='profiles/')),
                ('social_github', models.CharField(max_length=200, null=True, unique=True)),
                ('social_linkedin', models.CharField(max_length=200, null=True, unique=True)),
                ('social_website', models.CharField(max_length=200, null=True, unique=True)),
                ('social_twitter', models.CharField(max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
