# Generated by Django 4.0.1 on 2022-01-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.PositiveIntegerField(max_length=10, null=True),
        ),
    ]
