# Generated by Django 4.0.1 on 2022-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_announcement_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
