# Generated by Django 4.0.1 on 2022-03-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_announcement_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='event_time',
        ),
    ]
