# Generated by Django 4.0.1 on 2022-03-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_announcement_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='featured_image',
        ),
    ]
