# Generated by Django 4.0.1 on 2022-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_announcement_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announce_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
