# Generated by Django 4.0.1 on 2022-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_announcement_announce_image_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
