# Generated by Django 4.0.1 on 2022-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notes_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
