# Generated by Django 4.0.1 on 2022-03-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_notes_options_remove_notes_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('CSE', ' cse'), ('ECE', 'ece'), ('EEE', 'eee'), ('CIVIL', 'civil'), ('MECH', 'mech')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='semister',
            field=models.CharField(choices=[('1st', ' 1st Semister'), ('2nd', '2nd Semister'), ('3rd', '3rd Semister'), ('4th', '4th Semister'), ('5th', '5th Semister'), ('6th', '6th Semister'), ('7th', '7th Semister'), ('8th', '8th Semister')], max_length=30),
        ),
    ]
