# Generated by Django 4.0.1 on 2022-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
