# Generated by Django 4.0.1 on 2022-04-12 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_announcement_options_alter_notes_branch_and_more'),
        ('projects', '0007_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(default='profiles/male.png', null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('social_github', models.CharField(blank=True, max_length=200, null=True)),
                ('social_website', models.CharField(blank=True, max_length=200, null=True)),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_and_branch', models.CharField(blank=True, max_length=300, null=True)),
                ('college_year', models.CharField(blank=True, max_length=100, null=True)),
                ('college_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('intercollege_name', models.CharField(blank=True, max_length=200, null=True)),
                ('inter_course', models.CharField(blank=True, max_length=300, null=True)),
                ('inter_year', models.CharField(blank=True, max_length=100, null=True)),
                ('inter_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school_year', models.CharField(blank=True, max_length=100, null=True)),
                ('school_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_one', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_two', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_three', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_four', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_five', models.CharField(blank=True, max_length=200, null=True)),
                ('skill_six', models.CharField(blank=True, max_length=200, null=True)),
                ('experienceone_role', models.CharField(blank=True, max_length=200, null=True)),
                ('experienceone_duration', models.CharField(blank=True, max_length=200, null=True)),
                ('experienceone_company', models.CharField(blank=True, max_length=200, null=True)),
                ('experienceone_description', models.TextField(blank=True, null=True)),
                ('experiencetwo_role', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencetwo_duration', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencetwo_company', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencetwo_description', models.TextField(blank=True, null=True)),
                ('projectone_title', models.CharField(blank=True, max_length=200, null=True)),
                ('projectone_description', models.TextField(blank=True, null=True)),
                ('projectone_demolink', models.CharField(blank=True, max_length=200, null=True)),
                ('projecttwo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('projecttwo_description', models.TextField(blank=True, null=True)),
                ('projecttwo_demolink', models.CharField(blank=True, max_length=200, null=True)),
                ('projectthree_title', models.CharField(blank=True, max_length=200, null=True)),
                ('projectthree_description', models.TextField(blank=True, null=True)),
                ('projectthree_demolink', models.CharField(blank=True, max_length=200, null=True)),
                ('certificateone_title', models.CharField(blank=True, max_length=200, null=True)),
                ('certificateone_year', models.CharField(blank=True, max_length=20, null=True)),
                ('certificateone_description', models.TextField(blank=True, null=True)),
                ('certificatetwo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('certificatetwo_year', models.CharField(blank=True, max_length=20, null=True)),
                ('certificatetwo_description', models.TextField(blank=True, null=True)),
                ('language_one', models.CharField(blank=True, max_length=100, null=True)),
                ('language_two', models.CharField(blank=True, max_length=100, null=True)),
                ('language_three', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
