# Generated by Django 4.0.1 on 2022-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_resume_certificateone_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='resume',
            name='college_name',
            field=models.CharField(default=2000, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='college_percentage',
            field=models.CharField(default=2000, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='college_year',
            field=models.CharField(default=2000, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='course_and_branch',
            field=models.CharField(default=2000, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='inter_course',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='inter_percentage',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='inter_year',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='intercollege_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='mail',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='school_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='school_percentage',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='school_year',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='short_intro',
            field=models.TextField(default=2, max_length=800),
            preserve_default=False,
        ),
    ]
